### ISSUE TITLE
question: GIT commit ID?

### ISSUE THREAD

**Issue by jupe** [Strider-CD/strider-metadata#1]
Is there key for commit id?

**Comment by kfatehi** [comment]
Try ref.id

**Comment by jupe** [comment]
I cannot add that, maybe because sample data doesn't have ref.id ?

**Comment by kfatehi** [comment]
Ah you're right.. fixing it now.

**Comment by kfatehi** [comment]
Ok so I've conducted a small test to understand `job.ref.id` a bit more...

If you are doing a manual deploy, `job.ref.id` never gets set. If your deploy is triggered through a webhook, `job.ref.id` is in fact set to the sha1. 

However, because the sample data in strider-metadata is an extraction of the data structure of `job` during a Manual Deploy trigger and not a webhook trigger, that key was missing.

**Comment by kfatehi** [comment]
Now since the SHA1 is not included on manual trigger, you may consider using `GIT_COMMIT_HASH=$(git rev-parse HEAD)` to get the SHA1 during custom scripts. Otherwise, for webhooks, strider-metadata can now be used but please first upgrade strider-metadata to 0.0.3 (you can do this by going to Admin->Plugins in the UI and clicking Upgrade next to strider-metadata. If you prefer, you can also do this through npm).

HTH

**Comment by jupe** [comment]
Still cannot save new key, ADD button missing:
![image](https://cloud.githubusercontent.com/assets/3822425/5992004/55fd6f5a-aa1b-11e4-8f56-eb9fe435bdf9.png)

**Comment by kfatehi** [comment]
@jupe works for me, check that you're really running the newest version 

```
cat node_modules/strider-metadata/package.json | grep version
  "version": "0.0.3",
```

check if strider restarted correctly / restart strider

![screenshot 2015-02-01 14 11 09](https://cloud.githubusercontent.com/assets/175305/5992020/3c59dfec-aa1c-11e4-8970-14bd8cd956e4.png)

**Comment by jupe** [comment]
Same version.
`[../strider] # cat node_modules/strider-metadata/package.json | grep version
  "version": "0.0.3",`

ref.id works fine, but job.ref.id didn't . Which is Right ?

**Comment by jupe** [comment]
Sorry, yes ref.id it should be..

**Comment by kfatehi** [comment]
the plugin is drilling down into the `job` object, so you don't actually write `job.project.name` but rather `project.name` 

glad it is working for you now, let me know if you need anything else :+1:

**Comment by jupe** [comment]
I realized it soon after last comment :) . But Thanks for support :+1:

**Comment by macropin** [comment]
I just hit this issue. I probably wouldn't have wasted so much time had I not presumed that a GIT_HASH would be a required variable for any viable build system. To summarise the above dialogue: If you need to get the `GIT_HASH` in manually triggered builds. Add the following to your build script. Using the metadata plugin only works with webhook triggered builds.

```
export GIT_HASH=$(git rev-parse HEAD)
```

**Comment by knownasilya** [comment]
@macropin that would be a nice addition to strider, since there is no reason that manual builds cannot have the hash as well.. Would love a PR.
